---
name: update

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'self-hosted-console version'
        type: string
        default: "v0.0.3"
        required: false

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  GO_VERSION: "1.23"
  GO_LANGCI_LINT_VERSION: "v1.61.0"
  CONSOLE_VERSION: ${{ inputs.version }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_APP_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      -
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Update static files
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          make fetch
      -
        name: Push updated console
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'console'
